{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib)
    concatStringsSep
    mapAttrsToList
    mkEnableOption
    mkIf
    mkOption
    optionalString
    types
    ;

  cfg = config.programs.jaws;

  # Whether the user has configured any settings or providers
  hasSettings =
    cfg.settings.editor != null
    || cfg.settings.secretsPath != null
    || cfg.settings.cacheTtl != null
    || cfg.settings.defaultProvider != null
    || cfg.settings.maxVersions != null;

  hasProviders = cfg.providers != { };
  hasConfig = hasSettings || hasProviders;

  # Render the defaults line with inline KDL properties
  # Matches the output of Config::to_kdl() in src/config/loader.rs
  defaultsLine =
    "defaults"
    + optionalString (cfg.settings.editor != null) " editor=\"${cfg.settings.editor}\""
    + optionalString (cfg.settings.secretsPath != null) " secrets_path=\"${cfg.settings.secretsPath}\""
    + optionalString (cfg.settings.cacheTtl != null) " cache_ttl=${toString cfg.settings.cacheTtl}"
    + optionalString (
      cfg.settings.defaultProvider != null
    ) " default_provider=\"${cfg.settings.defaultProvider}\""
    + optionalString (
      cfg.settings.maxVersions != null
    ) " max_versions=${toString cfg.settings.maxVersions}";

  # Render a single provider block
  renderProvider =
    id: p:
    let
      children =
        optionalString (p.profile != null) "    profile \"${p.profile}\"\n"
        + optionalString (p.region != null) "    region \"${p.region}\"\n"
        + optionalString (p.vault != null) "    vault \"${p.vault}\"\n"
        + optionalString (p.organization != null) "    organization \"${p.organization}\"\n"
        + optionalString (p.tokenEnv != null) "    token-env \"${p.tokenEnv}\"\n";
    in
    "provider \"${id}\" kind=\"${p.kind}\" {\n${children}}";

  # Render the full KDL config file
  toKdl =
    let
      providerBlocks = concatStringsSep "\n\n" (mapAttrsToList renderProvider cfg.providers);
    in
    "// jaws configuration file\n// Generated by Home Manager\n\n${defaultsLine}\n"
    + optionalString hasProviders "\n${providerBlocks}\n";

  # Provider submodule type
  providerType = types.submodule {
    options = {
      kind = mkOption {
        type = types.enum [
          "aws"
          "onepassword"
          "bw"
        ];
        description = "Provider type.";
        example = "aws";
      };

      profile = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = ''
          AWS profile name. Use "all" to auto-discover all profiles
          from ~/.aws/credentials at runtime.
        '';
        example = "production";
      };

      region = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "AWS region.";
        example = "us-east-1";
      };

      vault = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = ''
          1Password vault ID, or Bitwarden project ID.
          Use "all" to auto-discover all vaults at runtime (1Password only).
        '';
        example = "all";
      };

      organization = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Bitwarden organization ID.";
      };

      tokenEnv = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = ''
          Name of the environment variable containing the authentication token.
          For 1Password: defaults to OP_SERVICE_ACCOUNT_TOKEN.
          For Bitwarden: defaults to BWS_ACCESS_TOKEN.
        '';
        example = "OP_SERVICE_ACCOUNT_TOKEN";
      };
    };
  };
in
{
  options.programs.jaws = {
    enable = mkEnableOption "jaws secrets manager";

    package = mkOption {
      type = types.package;
      default = pkgs.jaws;
      defaultText = lib.literalExpression "pkgs.jaws";
      description = ''
        The jaws package to install.
        The default assumes you have applied the jaws overlay to your pkgs.
      '';
    };

    settings = {
      editor = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Editor to use when editing secrets. Defaults to $EDITOR or vi.";
        example = "hx";
      };

      secretsPath = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Path where secrets are stored locally. Defaults to ./.secrets.";
        example = "./.secrets";
      };

      cacheTtl = mkOption {
        type = types.nullOr types.ints.unsigned;
        default = null;
        description = "Cache TTL in seconds. Defaults to 900 (15 minutes).";
        example = 900;
      };

      defaultProvider = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = ''
          Default provider for commands that accept a secret reference.
          When set, allows omitting the provider:// prefix.
        '';
        example = "jaws";
      };

      maxVersions = mkOption {
        type = types.nullOr types.ints.positive;
        default = null;
        description = ''
          Maximum number of local versions to keep per secret.
          Older versions are automatically pruned. Defaults to 10.
        '';
        example = 10;
      };
    };

    providers = mkOption {
      type = types.attrsOf providerType;
      default = { };
      description = ''
        Attribute set of provider configurations.
        The attribute name becomes the provider ID.
      '';
      example = lib.literalExpression ''
        {
          "aws" = {
            kind = "aws";
            profile = "all";
          };
          "op-dev" = {
            kind = "onepassword";
            vault = "abc123";
          };
        }
      '';
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile."jaws/jaws.kdl" = mkIf hasConfig {
      text = toKdl;
    };
  };
}
