//! Enrollment token management for client registration.
//!
//! Enrollment tokens are single-use, time-limited tokens that authorize
//! a client to receive a signed certificate from the server's CA.
//!
//! Tokens are validated against both an in-memory cache (for tokens generated
//! during this server session) and the database (for tokens generated by
//! `jaws serve --generate-token` in a separate process).

use std::collections::HashMap;
use std::sync::Mutex;

use chrono::{DateTime, Duration, Utc};

use crate::db::SecretRepository;
use crate::error::JawsError;
use crate::server::pki;

/// Default enrollment token validity (15 minutes).
const DEFAULT_TOKEN_LIFETIME_SECS: i64 = 900;

/// An enrollment token with metadata.
#[derive(Debug, Clone)]
#[allow(dead_code)]
struct EnrollmentToken {
    created_at: DateTime<Utc>,
    expires_at: DateTime<Utc>,
    used: bool,
    used_by: Option<String>,
}

/// Manages enrollment tokens and processes client enrollment.
pub struct EnrollmentManager {
    /// Active enrollment tokens (from this server session).
    tokens: Mutex<HashMap<String, EnrollmentToken>>,
    /// CA certificate PEM (for signing client certs and returning to clients).
    ca_cert_pem: String,
    /// CA private key PEM (for signing client certs).
    ca_key_pem: String,
    /// Database repository for persisting client records and token lookup.
    repo: SecretRepository,
}

impl EnrollmentManager {
    pub fn new(ca_cert_pem: String, ca_key_pem: String, repo: SecretRepository) -> Self {
        Self {
            tokens: Mutex::new(HashMap::new()),
            ca_cert_pem,
            ca_key_pem,
            repo,
        }
    }

    /// Generate a new enrollment token. Returns the token string.
    pub fn generate_token(&self) -> Result<String, JawsError> {
        let token = uuid::Uuid::new_v4().to_string();
        let now = Utc::now();
        let expires_at = now + Duration::seconds(DEFAULT_TOKEN_LIFETIME_SECS);

        let entry = EnrollmentToken {
            created_at: now,
            expires_at,
            used: false,
            used_by: None,
        };

        let mut tokens = self
            .tokens
            .lock()
            .map_err(|e| JawsError::Other(e.to_string()))?;
        tokens.insert(token.clone(), entry);

        // Also persist to DB so that tokens generated by --generate-token
        // (a separate process) share the same storage.
        let _ =
            self.repo
                .store_enrollment_token(&token, &now.to_rfc3339(), &expires_at.to_rfc3339());

        Ok(token)
    }

    /// Validate an enrollment token.
    ///
    /// Checks the in-memory cache first (for tokens generated during this
    /// server session), then falls back to the database (for tokens generated
    /// by `jaws serve --generate-token` in a separate process).
    fn validate_token(&self, token: &str) -> Result<(), JawsError> {
        // 1. Check in-memory cache
        {
            let tokens = self
                .tokens
                .lock()
                .map_err(|e| JawsError::Other(e.to_string()))?;

            if let Some(entry) = tokens.get(token) {
                if entry.used {
                    return Err(JawsError::validation(
                        "Enrollment token has already been used",
                    ));
                }
                if Utc::now() > entry.expires_at {
                    return Err(JawsError::validation("Enrollment token has expired"));
                }
                // Found and valid in memory
                return Ok(());
            }
        }

        // 2. Fallback: check the database
        match self.repo.validate_enrollment_token(token) {
            Ok(true) => Ok(()),
            Ok(false) => Err(JawsError::validation("Invalid enrollment token")),
            Err(e) => Err(JawsError::validation(format!(
                "Failed to validate enrollment token: {}",
                e
            ))),
        }
    }

    /// Mark a token as used in both the in-memory cache and the database.
    fn mark_token_used(&self, token: &str, client_id: &str) {
        // In-memory
        if let Ok(mut tokens) = self.tokens.lock() {
            if let Some(entry) = tokens.get_mut(token) {
                entry.used = true;
                entry.used_by = Some(client_id.to_string());
            }
        }

        // Database
        let _ = self.repo.mark_enrollment_token_used(token, client_id);
    }

    /// Process a client enrollment request.
    /// Validates the token, signs the CSR, records the client, and marks the token as used.
    /// If a client with the same name already exists (e.g. revoked), it is replaced.
    /// Returns (client_cert_pem, ca_cert_pem).
    pub fn process_enrollment(
        &self,
        token: &str,
        client_name: &str,
        csr_pem: &str,
    ) -> Result<(String, String), JawsError> {
        // Validate the token
        self.validate_token(token)?;

        // Sign the CSR
        let client_cert_pem =
            pki::sign_csr(&self.ca_cert_pem, &self.ca_key_pem, csr_pem, client_name)?;

        // Compute certificate fingerprint
        let fingerprint = pki::cert_fingerprint(&client_cert_pem)?;

        // Remove any existing client with the same name (e.g. previously revoked)
        // so re-enrollment works cleanly.
        match self.repo.delete_client_by_name(client_name) {
            Ok(n) if n > 0 => {
                eprintln!(
                    "  Replaced existing client '{}' ({} old record(s) removed)",
                    client_name, n
                );
            }
            _ => {}
        }

        // Record the new client in the database
        let client_id = uuid::Uuid::new_v4().to_string();
        self.repo
            .store_client(&client_id, client_name, &fingerprint, &client_cert_pem)?;

        // Mark the token as used
        self.mark_token_used(token, &client_id);

        // Log the enrollment
        let _ = self.repo.log_operation(
            "client_enrolled",
            "server",
            client_name,
            Some(&format!("fingerprint: {}", &fingerprint[..16])),
        );

        eprintln!(
            "  Client '{}' enrolled successfully (fingerprint: {}...)",
            client_name,
            &fingerprint[..16]
        );

        Ok((client_cert_pem, self.ca_cert_pem.clone()))
    }

    /// List all enrolled clients.
    pub fn list_clients(&self) -> Result<Vec<(String, String, bool)>, JawsError> {
        self.repo.list_clients()
    }

    /// Revoke a client by name.
    pub fn revoke_client(&self, client_name: &str) -> Result<bool, JawsError> {
        self.repo.revoke_client(client_name)
    }
}
