//! gRPC service implementation for the jaws server.
//!
//! Implements the `JawsService` trait generated by tonic-build, proxying
//! requests to the server's configured `SecretManager` providers.
//!
//! All RPCs except `Enroll` and `Ping` require a valid mTLS client certificate.
//! The server TLS is configured with `client_auth_optional(true)` so that
//! enrollment connections (which have no client cert yet) can still complete
//! the TLS handshake. Authentication is then enforced at the application layer.

use std::pin::Pin;
use std::sync::Arc;

use tokio_stream::Stream;
use tonic::{Request, Response, Status};

use crate::db::SecretRepository;
use crate::error::JawsError;
use crate::secrets::Provider;
use crate::server::auth::extract_client_identity;
use crate::server::enrollment::EnrollmentManager;

pub mod proto {
    tonic::include_proto!("jaws");
}

use proto::jaws_service_server::JawsService;
use proto::*;

/// The server-side implementation of the JawsService gRPC service.
pub struct JawsServiceImpl {
    /// All providers available on this server.
    providers: Arc<Vec<Provider>>,
    /// Server name (used in enrollment responses and ping).
    server_name: String,
    /// Enrollment manager for handling client enrollment.
    enrollment: Arc<EnrollmentManager>,
    /// Database repository for audit logging and client validation.
    repo: SecretRepository,
}

impl JawsServiceImpl {
    pub fn new(
        providers: Vec<Provider>,
        server_name: String,
        enrollment: Arc<EnrollmentManager>,
        repo: SecretRepository,
    ) -> Self {
        Self {
            providers: Arc::new(providers),
            server_name,
            enrollment,
            repo,
        }
    }

    /// Find a provider by ID.
    fn find_provider(
        &self,
        provider_id: &str,
    ) -> Result<&dyn crate::secrets::SecretManager, Status> {
        self.providers
            .iter()
            .find(|p| p.id() == provider_id)
            .map(|p| p.as_ref())
            .ok_or_else(|| Status::not_found(format!("Provider '{}' not found", provider_id)))
    }

    /// Require a valid, non-revoked client certificate on the request.
    /// Returns the client identity if valid, or a Status error.
    fn require_client_cert<T>(&self, request: &Request<T>) -> Result<String, Status> {
        let identity = extract_client_identity(request).ok_or_else(|| {
            Status::unauthenticated(
                "Client certificate required. Run 'jaws connect' to enroll with this server.",
            )
        })?;

        // Check if the client certificate is still valid (not revoked)
        match self.repo.is_client_valid(&identity.cert_fingerprint) {
            Ok(true) => Ok(identity.name),
            Ok(false) => Err(Status::permission_denied(
                "Client certificate has been revoked. Contact the server administrator.",
            )),
            Err(_) => {
                // DB error — be permissive if the client presented a CA-signed cert.
                // The TLS layer already verified the cert chain; the DB check is
                // an extra revocation layer. If the DB is unavailable, allow the
                // request rather than locking out all clients.
                Ok(identity.name)
            }
        }
    }

    /// Log a client action for auditing.
    fn log_client_action(
        &self,
        client_name: &str,
        operation: &str,
        provider_id: &str,
        secret_name: &str,
    ) {
        let details = format!("remote client: {}", client_name);
        let _ = self
            .repo
            .log_operation(operation, provider_id, secret_name, Some(&details));
    }
}

#[tonic::async_trait]
impl JawsService for JawsServiceImpl {
    // ── Enroll: no client cert required (this is how clients *get* one) ────
    async fn enroll(
        &self,
        request: Request<EnrollRequest>,
    ) -> Result<Response<EnrollResponse>, Status> {
        let req = request.into_inner();

        if req.token.is_empty() {
            return Err(Status::invalid_argument("Enrollment token is required"));
        }
        if req.csr_pem.is_empty() {
            return Err(Status::invalid_argument("CSR is required"));
        }
        if req.client_name.is_empty() {
            return Err(Status::invalid_argument("Client name is required"));
        }

        let (client_cert_pem, ca_cert_pem) = self
            .enrollment
            .process_enrollment(&req.token, &req.client_name, &req.csr_pem)
            .map_err(|e| Status::permission_denied(format!("Enrollment failed: {}", e)))?;

        Ok(Response::new(EnrollResponse {
            client_cert_pem,
            ca_cert_pem,
            server_name: self.server_name.clone(),
        }))
    }

    // ── Ping: no client cert required (health check / discovery) ──────────
    async fn ping(&self, _request: Request<PingRequest>) -> Result<Response<PingResponse>, Status> {
        Ok(Response::new(PingResponse {
            server_name: self.server_name.clone(),
            version: env!("CARGO_PKG_VERSION").to_string(),
            provider_count: self.providers.len() as i32,
        }))
    }

    // ── All remaining RPCs require a valid client certificate ──────────────

    async fn list_providers(
        &self,
        request: Request<ListProvidersRequest>,
    ) -> Result<Response<ListProvidersResponse>, Status> {
        self.require_client_cert(&request)?;

        let providers = self
            .providers
            .iter()
            .map(|p| ProviderInfo {
                id: p.id().to_string(),
                kind: p.kind().to_string(),
                supports_rollback: p.supports_rollback(),
                supports_remote_history: p.supports_remote_history(),
            })
            .collect();

        Ok(Response::new(ListProvidersResponse { providers }))
    }

    type ListSecretsStream =
        Pin<Box<dyn Stream<Item = Result<SecretEntry, Status>> + Send + 'static>>;

    async fn list_secrets(
        &self,
        request: Request<ListSecretsRequest>,
    ) -> Result<Response<Self::ListSecretsStream>, Status> {
        self.require_client_cert(&request)?;

        let req = request.into_inner();
        let provider = self.find_provider(&req.provider_id)?;

        let secrets = provider
            .list_all()
            .await
            .map_err(|e| Status::internal(format!("Failed to list secrets: {}", e)))?;

        let stream = tokio_stream::iter(secrets.into_iter().map(|name| Ok(SecretEntry { name })));

        Ok(Response::new(Box::pin(stream)))
    }

    async fn get_secret(
        &self,
        request: Request<GetSecretRequest>,
    ) -> Result<Response<GetSecretResponse>, Status> {
        let client_name = self.require_client_cert(&request)?;
        let req_inner = request.get_ref().clone();
        self.log_client_action(
            &client_name,
            "remote_get",
            &req_inner.provider_id,
            &req_inner.name,
        );

        let provider = self.find_provider(&req_inner.provider_id)?;
        let value = provider
            .get_secret(&req_inner.name)
            .await
            .map_err(|e| match e {
                JawsError::NotFound(msg) => Status::not_found(msg),
                JawsError::Provider { provider, message } => {
                    Status::internal(format!("Provider '{}': {}", provider, message))
                }
                _ => Status::internal(e.to_string()),
            })?;

        Ok(Response::new(GetSecretResponse { value }))
    }

    async fn create_secret(
        &self,
        request: Request<CreateSecretRequest>,
    ) -> Result<Response<CreateSecretResponse>, Status> {
        let client_name = self.require_client_cert(&request)?;
        let req_inner = request.get_ref().clone();
        self.log_client_action(
            &client_name,
            "remote_create",
            &req_inner.provider_id,
            &req_inner.name,
        );

        let provider = self.find_provider(&req_inner.provider_id)?;
        let description = if req_inner.description.is_empty() {
            None
        } else {
            Some(req_inner.description.as_str())
        };

        let version_id = provider
            .create(&req_inner.name, &req_inner.value, description)
            .await
            .map_err(|e| Status::internal(format!("Failed to create secret: {}", e)))?;

        Ok(Response::new(CreateSecretResponse { version_id }))
    }

    async fn update_secret(
        &self,
        request: Request<UpdateSecretRequest>,
    ) -> Result<Response<UpdateSecretResponse>, Status> {
        let client_name = self.require_client_cert(&request)?;
        let req_inner = request.get_ref().clone();
        self.log_client_action(
            &client_name,
            "remote_update",
            &req_inner.provider_id,
            &req_inner.name,
        );

        let provider = self.find_provider(&req_inner.provider_id)?;
        let version_id = provider
            .update(&req_inner.name, &req_inner.value)
            .await
            .map_err(|e| Status::internal(format!("Failed to update secret: {}", e)))?;

        Ok(Response::new(UpdateSecretResponse { version_id }))
    }

    async fn delete_secret(
        &self,
        request: Request<DeleteSecretRequest>,
    ) -> Result<Response<DeleteSecretResponse>, Status> {
        let client_name = self.require_client_cert(&request)?;
        let req_inner = request.get_ref().clone();
        self.log_client_action(
            &client_name,
            "remote_delete",
            &req_inner.provider_id,
            &req_inner.name,
        );

        let provider = self.find_provider(&req_inner.provider_id)?;
        provider
            .delete(&req_inner.name, req_inner.force)
            .await
            .map_err(|e| Status::internal(format!("Failed to delete secret: {}", e)))?;

        Ok(Response::new(DeleteSecretResponse {}))
    }

    async fn rollback_secret(
        &self,
        request: Request<RollbackSecretRequest>,
    ) -> Result<Response<RollbackSecretResponse>, Status> {
        let client_name = self.require_client_cert(&request)?;
        let req_inner = request.get_ref().clone();
        self.log_client_action(
            &client_name,
            "remote_rollback",
            &req_inner.provider_id,
            &req_inner.name,
        );

        let provider = self.find_provider(&req_inner.provider_id)?;
        if !provider.supports_rollback() {
            return Err(Status::unimplemented(format!(
                "Provider '{}' does not support rollback",
                req_inner.provider_id
            )));
        }

        let version_id_opt = if req_inner.version_id.is_empty() {
            None
        } else {
            Some(req_inner.version_id.as_str())
        };

        let restored = provider
            .rollback(&req_inner.name, version_id_opt)
            .await
            .map_err(|e| Status::internal(format!("Failed to rollback: {}", e)))?;

        Ok(Response::new(RollbackSecretResponse {
            restored_version_id: restored,
        }))
    }
}
