# documentation at https://goreleaser.com
project_name: jaws
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/jaws
    binary: jaws
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X 'main.Version={{ .Version }}' -X 'main.Date={{ time "2006-01-02" }}'
    goos:
      - linux
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-rc"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^ci'
